disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - empty_string

excluded:
  - Carthage
  - Pods
  - SwiftLint
  - .build
  - DerivedData

line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 60
  error: 100
